<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <h2 id="hello-world"><a href="#hello-world">👋 Hello World</a></h2>
    <div class="flex gap4 flex-wrap py4">
      <span>Hello Wêreld!</span>
      <span>Përshendetje Botë!</span>
      <span>ሰላም ልዑል!</span>
      <span>مرحبا بالعالم!</span>
      <span>Բարեւ աշխարհ!</span>
      <span>Kaixo Mundua!</span>
      <span>Прывітанне Сусвет!</span>
      <span>ওহে বিশ্ব!</span>
      <span>Здравей свят!</span>
      <span>Hola món!</span>
      <span>Moni Dziko Lapansi!</span>
      <span>你好世界！</span>
      <span>Pozdrav svijete!</span>
      <span>Ahoj světe!</span>
      <span>Hej Verden!</span>
      <span>Hallo Wereld!</span>
      <span>Hello World!</span>
      <span>Tere maailm!</span>
      <span>Hei maailma!</span>
      <span>Bonjour monde!</span>
      <span>Hallo wrâld!</span>
      <span>გამარჯობა მსოფლიო!</span>
      <span>Hallo Welt!</span>
      <span>Γειά σου Κόσμε!</span>
      <span>Sannu Duniya!</span>
      <span>שלום עולם!</span>
      <span>नमस्ते दुनिया!</span>
      <span>Helló Világ!</span>
      <span>Halló heimur!</span>
      <span>Ndewo Ụwa!</span>
      <span>Halo Dunia!</span>
      <span>Ciao mondo!</span>
      <span>こんにちは世界！</span>
      <span>Сәлем Әлем!</span>
      <span>សួស្តី​ពិភពលោក!</span>
      <span>Салам дүйнө!</span>
      <span>ສະ​ບາຍ​ດີ​ຊາວ​ໂລກ!</span>
      <span>Sveika pasaule!</span>
      <span>Labas pasauli!</span>
      <span>Moien Welt!</span>
      <span>Здраво свету!</span>
      <span>Hai dunia!</span>
      <span>ഹലോ വേൾഡ്!</span>
      <span>Сайн уу дэлхий!</span>
      <span>မင်္ဂလာပါကမ္ဘာလောက!</span>
      <span>नमस्कार संसार!</span>
      <span>Hei Verden!</span>
      <span>سلام نړی!</span>
      <span>سلام دنیا!</span>
      <span>Witaj świecie!</span>
      <span>Olá Mundo!</span>
      <span>ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ ਦੁਨਿਆ!</span>
      <span>Salut Lume!</span>
      <span>Привет мир!</span>
      <span>Hàlo a Shaoghail!</span>
      <span>Здраво Свете!</span>
      <span>Lefatše Lumela!</span>
      <span>හෙලෝ වර්ල්ඩ්!</span>
      <span>Pozdravljen svet!</span>
      <span>¡Hola Mundo!</span>
      <span>Halo Dunya!</span>
      <span>Salamu Dunia!</span>
      <span>Hej världen!</span>
      <span>Салом Ҷаҳон!</span>
      <span>สวัสดีชาวโลก!</span>
      <span>Selam Dünya!</span>
      <span>Привіт Світ!</span>
      <span>Salom Dunyo!</span>
      <span>Chào thế giới!</span>
      <span>Helo Byd!</span>
      <span>Molo Lizwe!</span>
      <span>העלא וועלט!</span>
      <span>Mo ki O Ile Aiye!</span>
      <span>Sawubona Mhlaba!</span>
    </div>

    <h2 id="hello-world-from-fav-languages">
      <a href="#hello-world-from-fav-languages">👋 Hello World from fav Languages</a>
    </h2>
    <div class="code-block titled showLineNumber">
      <h2 class="code-title">example.py</h2>
      <CodeCopy>
        <pre><code
            class="language-python">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="line-number">1</span><span class="no-line-diff"></span></div><div class="code-content"><span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">)</span><span class="token punctuation">:</span></div></div><div class="code-line"><div class="code-linenotation"><span class="line-number">2</span><span class="no-line-diff"></span></div><div class="code-content">    <span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'Hello, World #%s'</span> <span class="token operator">%</span> <span class="token punctuation">(</span>i<span class="token punctuation">)</span><span class="token punctuation">)</span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <div class="code-block titled showLineNumber">
      <h2 class="code-title">example.c</h2>
      <CodeCopy>
        <pre><code
            class="language-c">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="line-number">1</span><span class="no-line-diff"></span></div><div class="code-content"><span class="token macro property"><span class="token directive-hash">#</span><span class="token directive keyword">include</span> <span class="token string">&lt;stdio.h></span></span></div></div><div class="code-line"><div class="code-linenotation"><span class="line-number">2</span><span class="no-line-diff"></span></div><div class="code-content"></div></div><div class="code-line"><div class="code-linenotation"><span class="line-number">3</span><span class="no-line-diff"></span></div><div class="code-content"><span class="token keyword">int</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></div></div><div class="code-line"><div class="code-linenotation"><span class="line-number">4</span><span class="no-line-diff"></span></div><div class="code-content">    <span class="token function">printf</span><span class="token punctuation">(</span><span class="token string">"Hello, World from C!\n"</span><span class="token punctuation">)</span><span class="token punctuation">;</span></div></div><div class="code-line"><div class="code-linenotation"><span class="line-number">5</span><span class="no-line-diff"></span></div><div class="code-content">    <span class="token keyword">return</span> <span class="token number">0</span><span class="token punctuation">;</span></div></div><div class="code-line"><div class="code-linenotation"><span class="line-number">6</span><span class="no-line-diff"></span></div><div class="code-content"><span class="token punctuation">}</span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <div class="code-block titled showLineNumber">
      <h2 class="code-title">example.cpp</h2>
      <CodeCopy>
        <pre><code
            class="language-cpp">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="line-number">1</span><span class="no-line-diff"></span></div><div class="code-content"><span class="token macro property"><span class="token directive-hash">#</span><span class="token directive keyword">include</span> <span class="token string">&lt;iostream></span></span></div></div><div class="code-line"><div class="code-linenotation"><span class="line-number">2</span><span class="no-line-diff"></span></div><div class="code-content"></div></div><div class="code-line"><div class="code-linenotation"><span class="line-number">3</span><span class="no-line-diff"></span></div><div class="code-content"><span class="token keyword">int</span> <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></div></div><div class="code-line"><div class="code-linenotation"><span class="line-number">4</span><span class="no-line-diff"></span></div><div class="code-content">    std<span class="token double-colon punctuation">::</span>cout <span class="token operator">&lt;&lt;</span> <span class="token string">"Hello, World from C++!"</span> <span class="token operator">&lt;&lt;</span> std<span class="token double-colon punctuation">::</span>endl<span class="token punctuation">;</span></div></div><div class="code-line"><div class="code-linenotation"><span class="line-number">5</span><span class="no-line-diff"></span></div><div class="code-content">    <span class="token keyword">return</span> <span class="token number">0</span><span class="token punctuation">;</span></div></div><div class="code-line"><div class="code-linenotation"><span class="line-number">6</span><span class="no-line-diff"></span></div><div class="code-content"><span class="token punctuation">}</span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <div class="code-block titled showLineNumber">
      <h2 class="code-title">example.rs</h2>
      <CodeCopy>
        <pre><code
            class="language-rust">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="line-number">1</span><span class="no-line-diff"></span></div><div class="code-content"><span class="token keyword">fn</span> <span class="token function-definition function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span></div></div><div class="code-line"><div class="code-linenotation"><span class="line-number">2</span><span class="no-line-diff"></span></div><div class="code-content">    <span class="token macro property">println!</span><span class="token punctuation">(</span><span class="token string">"Hello, World from Rust!"</span><span class="token punctuation">)</span><span class="token punctuation">;</span></div></div><div class="code-line"><div class="code-linenotation"><span class="line-number">3</span><span class="no-line-diff"></span></div><div class="code-content"><span class="token punctuation">}</span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <h2 id="end"><a href="#end">👍 END</a></h2>
    <p>With warm hello , i would like to start sharing my learnings here</p>
  </article>
</Post>
